---
# tasks file for createVMs
- include_vars:
    file: "../../../vars/vault"
    name: Vaults vars
- include_vars:
    file: "../../../vars/main.yml"
    name: Main vars to include
    
- name: Install virt-install
  dnf:
    name: virt-install
    state: latest
  
- name: Clean out old bootstrap
  command: "virsh destroy {{ item.name }}"
  with_items:
    - "{{  nodes.bootstrap  }}"
    - "{{  nodes.masters  }}"
    - "{{  nodes.workers  }}"
  ignore_errors: yes

- name: Clean out old bootstrap
  command: "virsh undefine --nvram {{ item.name }}"
  with_items:
    - "{{  nodes.bootstrap  }}"
    - "{{  nodes.masters  }}"
    - "{{  nodes.workers  }}"
  ignore_errors: yes

- name: Remove QCOWs
  file:
    path: "/var/lib/libvirt/images/{{ item.name }}.qcow2"
    state: absent
  with_items:
    - "{{  nodes.bootstrap  }}"
    - "{{  nodes.masters  }}"
    - "{{  nodes.workers  }}"
  ignore_errors: yes

- name: Setup OCP Bootstrap & Master VMs
  command: "virt-install
    --name {{ item.name }}
    --disk size=120
    --ram 16384
    --cpu host
    --vcpus 4
    --os-type linux
    --os-variant rhel8.2
    --network network=br0,mac={{ item.macaddr }}
    --boot uefi
    --pxe
    --noautoconsole"
  with_items:
    - "{{  nodes.bootstrap  }}"
    - "{{  nodes.masters  }}"

- name: Setup OCP Worker VMs
  command: "virt-install
    --name {{ item.name }}
    --disk size=120
    --disk path=/var/lib/libvirt/images/{{ item.name }}-osd,size=200
    --ram 16384
    --cpu host
    --vcpus 4
    --os-type linux
    --os-variant rhel8.2
    --network network=br0,mac={{ item.macaddr }}
    --boot uefi
    --pxe
    --noautoconsole"
  with_items:
    - "{{  nodes.workers  }}"
