---
srv_interface: "enp3s0"
srv_ip: "192.168.1.2"
nodes_subnet24: "192.168.1"
baseName: "lab"
baseDomain: "local"

nodes:
  bootstrap:
    - name: "bootstrap"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.10"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.1"
      macaddr: "52:54:00:d8:6f:16"
      disk: "vda"
      boot: "uefi"
      nic_pxe: enp1s0
  masters:
    - name: "master1"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.11"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.1"
      macaddr: "0c:c4:7a:20:60:c8"
      disk: "vda"
      boot: "uefi"
      nic_pxe: enp1s0
    - name: "master2"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.12"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.1"
      macaddr: "0c:c4:7a:20:61:c8"
      disk: "vda"
      boot: "uefi"
      nic_pxe: enp1s0
    - name: "master3"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.13"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.1"
      macaddr: "3c:fd:fe:9e:7e:21"
      disk: "vda"
      boot: "uefi"
      nic_pxe: enp1s0
  workers:
    - name: "worker1"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.21"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.1"
      macaddr: "3c:fd:fe:9e:7b:a9"
      disk: "vda"
      boot: "uefi"
      nic_pxe: enp1s0
    - name: "worker2"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.22"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.1"
      macaddr: "3c:fd:fe:aa:46:60"
      disk: "vda"
      boot: "uefi"
      nic_pxe: enp1s0
    - name: "worker3"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.23"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.1"
      macaddr: "3c:fd:fe:ab:b0:38"
      disk: "vda"
      boot: "uefi"
      nic_pxe: enp1s0
    - name: "worker4"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.24"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.1"
      macaddr: "3c:ec:ef:40:d0:24"
      disk: "nvme0n1"
      boot: "uefi"
      nic_pxe: eno7
  extra:
    - name: "netsrv"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.2"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.1"
      macaddr: "1c:69:7a:38:a9:87"
      disk: "nvme0n1"
      boot: "uefi"
    - name: "kvm1"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.3"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.1"
      macaddr: "10:7b:44:91:a2:7c"
      disk: "nvme0n1"
      boot: "uefi"
    - name: "sat"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.5"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.1"
      macaddr: "52:54:00:17:e1:87"
      disk: "vda"
      boot: "bios"
    - name: "tower"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.6"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.1"
      macaddr: "52:54:00:f5:b5:fa"
      disk: "vda"
      boot: "bios"
    - name: "cloudkey"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.30"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.1"
      macaddr: "74:83:c2:17:45:53"
      disk: "sda"
      boot: "bios"
    - name: "switch1"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.31"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.1"
      macaddr: "fc:ec:da:78:ad:ed"
      disk: "sda"
      boot: "bios"
    - name: "switch2"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.32"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.1"
      macaddr: "f0:9f:c2:68:26:ee"
      disk: "sda"
      boot: "bios"
    - name: "lowerap"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.33"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.1"
      macaddr: "74:83:c2:da:2e:0c"
      disk: "sda"
      boot: "bios"
    - name: "upperap"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.34"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.1"
      macaddr: "74:83:c2:da:2e:6c"
      disk: "sda"
      boot: "bios"
    - name: "iptv"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.35"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.1"
      macaddr: "ac:6f:bb:5d:58:d6"
      disk: "sda"
      boot: "bios"
    - name: "nas1"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.20"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.1"
      macaddr: "00:11:32:b4:b2:a3"
      disk: "sda"
      boot: "bios"

dhcp:
  gateway: "{{ nodes_subnet24 | default ('192.168.126')}}.1"
  broadcast: "{{ nodes_subnet24 | default ('192.168.126')}}.255"
  netmask: "255.255.255.0"
  poolstart: "{{ nodes_subnet24 | default ('192.168.126')}}.128"
  poolend: "{{ nodes_subnet24 | default ('192.168.126')}}.254"
  subnet: "{{ nodes_subnet24 | default ('192.168.126')}}.0"

ocp_mirror: "https://mirror.openshift.com/pub/openshift-v4"

ocp_metal: "{{ ocp_mirror }}/dependencies/rhcos/4.{{ ocp_release.split('.')[1] | lower }}/latest/rhcos-{{ ocp_release }}-x86_64-metal.x86_64.raw.gz"
ocp_initramfs: "{{ ocp_mirror }}/dependencies/rhcos/4.{{ ocp_release.split('.')[1] | lower }}/latest/rhcos-{{ ocp_release }}-x86_64-installer-initramfs.x86_64.img"
ocp_kernel: "{{ ocp_mirror }}/dependencies/rhcos/4.{{ ocp_release.split('.')[1] | lower }}/latest/rhcos-{{ ocp_release }}-x86_64-installer-kernel-x86_64"

ign_folder: /var/www/html/ignition
ocp_install_path: "/root/ocp"

ocp_folders:
  - "{{ ign_folder }}"
  - "{{ ocp_install_path }}"
  - "{{ folders_pxe }}"
  - /root/bin

ocp_release: "4.5.2"

#https://unix.stackexchange.com/questions/363878/which-selinux-policies-apply-to-haproxy
selinux_policy: targeted
selinux_state: enforcing
selinux_ports:
  - { ports: '6443', proto: 'tcp', setype: 'http_port_t', state: 'present' }
  - { ports: '22623', proto: 'tcp', setype: 'http_port_t', state: 'present' }
  - { ports: '9000', proto: 'tcp', setype: 'http_port_t', state: 'present' }
  - { ports: '8080', proto: 'tcp', setype: 'http_port_t', state: 'present' }
  
#check results via semanage port -l | grep -E 'http_cache_port_t|commplex_main_port_t|http_port_t'

mount_point: /tmp/iso
efi_dir: "{{ mount_point }}/EFI/BOOT"
bios_dir: /usr/share/syslinux
boot_dir: "{{ mount_point }}/images/pxeboot"
boot_iso: rhel8.2.iso
rhel_version: RHEL-8.2

efifiles:
  - BOOTX64.EFI
  - grubx64.efi
biosfiles:
  - pxelinux.0
  - ldlinux.c32
  - menu.c32
  - libutil.c32
rhel_bootfiles:
  - initrd.img
  - vmlinuz
tftp_dir: /var/lib/tftpboot
folders_pxe:
  - "{{ tftp_dir }}"
  - "{{ tftp_dir }}/uefi"
  - "{{ tftp_dir }}/{{ rhel_version }}"
  - "{{ tftp_dir }}/pxelinux"
  - "{{ tftp_dir }}/pxelinux/pxelinux.cfg"
  - /var/www/html/images
  - /var/www/html/kickstarts
  - "/var/www/html/{{ rhel_version }}"