---
- include_vars: "../../../vars/vault"
- include_vars: "../../../vars/main.yml"

- name: Set servers to boot from network on net boot
  ipmi_boot:
    name: "{{ item }}"
    user: "{{ vault_ipmiuser }}"
    password: "{{ vault_ipmipass }}"
    bootdev: network
    uefiboot: yes
  with_items:
    - 10.250.254.95
    - 10.250.254.97
    - 10.250.254.98

- name: Set servers to power on
  ipmi_power:
    name: "{{ item }}"
    user: "{{ vault_ipmiuser }}"
    password: "{{ vault_ipmipass }}"
    state: boot
  with_items:
    - 10.250.254.95
    - 10.250.254.97
    - 10.250.254.98