---
- include_vars: "../../../vars/vault"
- include_vars: "../../../vars/main.yml"
- name: Power Off
  redfish_command:
    category: Systems
    command: PowerForceOff
    baseuri: 192.168.1.42
    username: admin
    password: "{{ vault_bmc_pass }}"

- name: Set server to PXE boot
  redfish_command:
    category: Systems
    command: SetOneTimeBoot
    bootdevice: "Pxe"
    baseuri: "192.168.1.42"
    username: admin
    password: "{{ vault_bmc_pass }}"

#- name: Power On
#  redfish_command:
#    category: Systems
#    command: PowerOn
#    baseuri: 192.168.1.42
#    username: admin
#    password: "{{ vault_bmc_pass }}"